BOARD_MARKER = "Board:"
COMMANDS_MARKER = "Commands:"

CMD_CLICK = "click"
CMD_WAIT = "wait"
CMD_PRINT = "print"
CMD_PRINT_BOARD_ARG = "board"
CMD_JUMP = "jump"

KING_KIND = "K"
QUEEN_KIND = "Q"
ROOK_KIND = "R"
BISHOP_KIND = "B"
KNIGHT_KIND = "N"
PAWN_KIND = "P"

CELL_SIZE = 100
MOVE_TIME_PER_CELL = 1000
JUMP_TIME_MS = 1000
